on:
  push:
    branches:
      - "build-arm"

jobs:
  goreleaser-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Unshallow
        run: git fetch --prune --unshallow

      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: "v0.183.0"
          args: build --rm-dist --snapshot --config deploy/.goreleaser.yaml
